run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - bodyclose
    - errorlint
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
